language: generic
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="devon4net"
    - REPO_DEST="devon4net.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: ZhDofXkVqMzOnLGrQuu/moSoVl43G6L9IF1SX6YQIeKGd729LDP9mpyWT6g2FVUneBRw+oqNhr3Ur0o0S5Lv2zPsgO8AwMjCTML87kjGUlF3QbbSoeG+nW6oG9RM2TAsPwJAXnFJ7yQjK1PMX1oYHP6018i8xu5DbHB6UIqDeHWEvY+ZzHGUfs2fvoaWIqfa62g9O3pu2/3sAlsHO7dPjmk+rv/nP5/t9rBQnM3k75dBLTZYg6xVGk/qp1mXWU2R98jJb6Gqpov4pBroXLq5AZmYgeFnh4+wXn5ET2XNH1MTA1bK5WiinLLSF8WxHQ1oiUaXY82kMB1xJ3jDnkBCtJ/AI8qnYxY0G8TMXW5kq3amyoBl+AOoQhWf3dIOQ0eyo4Y7MKGzPlKWdSLi99hLXaBe0zc4SYOfmVK7Z/7qX+fN1v3jePiSwP6E+Ey9ndksG98y1q1VurIcbgFSvlp4jC702cIuNI2BOXlYvx+ecZhTxrMGMBUpFNrPO8fc64RlI1zzhUOsUmFWdhqH9D8aOGukC7fwsmdWcFojahqc/3Ldlw0F+wEU3EEmtElT8IRNqtVOEpiaVXbRtmpvG469ln/Hkv2hOL6WDWtewpm5Jz+/Znp5WEnSGCGSsxmuCyOaoH7pYQL7IeyEtianLYoK6lOZFtWvh6L9bdihhVqK/cY=
stages:
  - name: Documentation
    if: (branch = develop) AND (type = push)
jobs:
  include:
    - stage: Documentation
      script:
        # Clone repositories
        - git clone -b develop --single-branch https://${GH_REPO_SOURCE}
        - git clone https://${GH_REPO_DEST}
        - git clone https://${GH_REPO_CONSOLIDATE}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
            cd ../${REPO_CONSOLIDATE}
            if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
            git submodule init
            git submodule update --recursive --remote
            cd ${REPO_DEST}
            git checkout master
            git pull
            cd ..
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
            git push origin-wiki master
          fi
